"""
Central data access layer.

In this prototype, data is loaded from JSON fixtures generated by
data/generate_mock_data.py. Each accessor is written so that swapping the
in-memory store for a real Neo4j + PostgreSQL backing store only requires
changing this file: routers and services never touch the JSON files directly.
"""
import json
import os
from functools import lru_cache
from pathlib import Path

FIXTURES_DIR = Path(__file__).resolve().parent.parent / "fixtures"


@lru_cache(maxsize=None)
def _load(name: str):
    path = FIXTURES_DIR / f"{name}.json"
    with open(path, "r") as f:
        return json.load(f)


class DataStore:
    """Thin repository facade over the fixture data."""

    @property
    def teams(self):
        return _load("teams")

    @property
    def employees(self):
        return _load("employees")

    @property
    def repos(self):
        return _load("repos")

    @property
    def pull_requests(self):
        return _load("pull_requests")

    @property
    def tickets(self):
        return _load("tickets")

    @property
    def docs(self):
        return _load("docs")

    @property
    def conversations(self):
        return _load("conversations")

    @property
    def decisions(self):
        return _load("decisions")

    @property
    def incidents(self):
        return _load("incidents")

    @property
    def releases(self):
        return _load("releases")

    @property
    def dependency_graph(self):
        return _load("dependency_graph")

    @property
    def risks(self):
        return _load("risks")

    @property
    def ai_insights(self):
        return _load("ai_insights")

    @property
    def dashboard_summary(self):
        return _load("dashboard_summary")

    @property
    def projects(self):
        return _load("projects")

    def employee_by_id(self, employee_id: str):
        return next((e for e in self.employees if e["id"] == employee_id), None)

    def employees_by_ids(self, ids):
        idset = set(ids)
        return [e for e in self.employees if e["id"] in idset]


store = DataStore()
